apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
  {{- if .Values.deployment.updateStrategy }}
  strategy: {{- toYaml .Values.deployment.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" ( dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "xandikos.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "python3"
            - "-m"
            - "xandikos.web"
            - "--directory=/data"
            - "--listen-address=0.0.0.0"
            - "--port=8080"
            - "--metrics-port=8081"
            - "--defaults"
          env:
            - name: USER
              value: xandikos
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8081
      {{- if .Values.deployment.securityContext }}
      securityContext: {{- toYaml .Values.deployment.securityContext | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "xandikos.claimName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
