apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    # Disable the Traefik dashboard for security purposes
    ingressRoute:
      dashboard:
        enabled: false

    deployment:
      kind: DaemonSet

    ports:
      web:
        port: 80
        hostPort: 80
      websecure:
        port: 443
        hostPort: 443

    service:
      enabled: false
